spring:
  config:
    import: optional:file:.env[.properties]
application:
  api:
    url: http://api.weatherapi.com/v1/current.json
    key: ${API_KEY}
  view:
    window:
      width: 700
      height: 600
