spring:
  config:
    import: optional:file:.env[.properties]
application:
  api:
    url: http://api.weatherapi.com/v1/
    data_format: json
    key: ${API_KEY}
  view:
    window:
      width: 840
      height: 478
